Packaging
web-telescope/survey6 pull request #16
Opened 2022-08-11 14:13 UTC by dhruvi29

# Description
It is a debian package for cnc-server. 

## Fixes #14 
This PR closes #14 

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2022-08-11 14:18 UTC, dhruvi29 commented
1. How do I manage environment variables in packaging? 
2. Where do I store the logs?
3. I am packaging the tool with **stdeb**, how can I write a postinst script? (I want to write a postinst to add the tool to system service)

2022-08-14 14:56 UTC, maanas-talwar commented
@dhruvi29 you can check this out
1. Environment variables can be present in a `.env` file from where they can be taken up or they can be exported via the initialisation script.
2. Logs need to be stored in a separate logs directory.
3. You can check [this out](https://askubuntu.com/questions/101962/how-to-run-a-script-only-during-first-install-of-a-package-and-not-during-upgrad).

2022-08-28 15:23 UTC, maanas-talwar requested changes

2022-08-28 15:23 UTC, maanas-talwar commented on C&C Server/server.service
> +ExecStart=/bin/bash -c 'python /usr/lib/python3/dist-packages/src/main/App.py'
Why do we have the absolute path here?
This might create problems when others try to run the same things.

2022-08-28 15:23 UTC, maanas-talwar commented on C&C Server/src/main/data/ArchiveDao.py
> +      self.__db.query("CREATE TABLE IF NOT EXISTS ClientArchives (id INTEGER AUTO_INCREMENT , hostname TEXT PRIMARY KEY, lastActiveTime TIMESTAMP)",{})
Instead of an auto-increment integer for a key use UUID for it

2022-08-28 15:23 UTC, maanas-talwar commented on C&C Server/src/main/data/ClientDao.py
> +      self.__db.query("CREATE TABLE IF NOT EXISTS CurrentClients (id INTEGER AUTO_INCREMENT, hostname TEXT PRIMARY KEY, registrationEpochTime TIMESTAMP, lastActiveTime TIMESTAMP, currentStatus BOOLEA
Auto increment to UUID and hostname is the primary key here which should not be the case

2022-09-04 03:42 UTC, dhruvi29 commented on C&C Server/server.service
> +ExecStart=/bin/bash -c 'python /usr/lib/python3/dist-packages/src/main/App.py'
done

2022-09-04 05:45 UTC, dhruvi29 commented on C&C Server/src/main/data/ArchiveDao.py
> +      self.__db.query("CREATE TABLE IF NOT EXISTS ClientArchives (id INTEGER AUTO_INCREMENT , hostname TEXT PRIMARY KEY, lastActiveTime TIMESTAMP)",{})
Changed

2022-09-04 05:46 UTC, dhruvi29 commented on C&C Server/src/main/data/ClientDao.py
> +      self.__db.query("CREATE TABLE IF NOT EXISTS CurrentClients (id INTEGER AUTO_INCREMENT, hostname TEXT PRIMARY KEY, registrationEpochTime TIMESTAMP, lastActiveTime TIMESTAMP, currentStatus BOOLEA
Changed :+1: Had to refactor proto def so we can return uid to the probe which it has to store and send to the server for disconnection

2022-09-10 01:32 UTC, merged